wireless-connection:
  type: 5g_rel15
  latency: 1
  bandwidth: 10000
  jitter: 1
  packet-loss: 0.001
  reliability: 0.999
  availability: 0.9999
  qos-level: high
  energy-efficiency: high
  compatibility: fully-compatible
  cost: 100
  scalability: high
  security-level: high