wired-connection:
  type: usb30
  latency: 5
  bandwidth: 4800
  jitter: 8
  packet-loss: 0.005
  reliability: 0.98
  availability: 0.99
  qos-level: high
  energy-efficiency: medium
  compatibility: fully-compatible
  cost: 25
  scalability: high
  security-level: high
