wireless-connection:
  type: wifi4
  latency: 5
  bandwidth: 600
  jitter: 10
  packet-loss: 0.02
  reliability: 0.95
  availability: 0.98
  qos-level: medium
  energy-efficiency: medium
  compatibility: partially-compatible
  cost: 10
  scalability: medium
  security-level: medium