wireless-connection:
  type: wifi6
  latency: 2
  bandwidth: 9600
  jitter: 5
  packet-loss: 0.01
  reliability: 0.98
  availability: 0.99
  qos-level: high
  energy-efficiency: high
  compatibility: fully-compatible
  cost: 30
  scalability: high
  security-level: high