<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:robot-network-topology="urn:ietf:params:xml:ns:yang:robot-network-topology"
       xmlns:layer1="urn:ietf:params:xml:ns:yang:layer1"
       xmlns:layer2="urn:ietf:params:xml:ns:yang:layer2"
       name="cat5e">

    <xacro:property name="cat5e_yaml_file" value="$(find interface-description)/config/cat5e.yaml" />
    <xacro:property name="cat5e_props" value="${xacro.load_yaml(cat5e_yaml_file)}"/>
    <xacro:property name="cat5e_length" value="${cat5e_props['wired-connection']['length']}"/>
    <xacro:property name="cat5e_bandwidth" value="${cat5e_props['wired-connection']['bandwidth']}"/>
    <xacro:property name="cat5e_jitter" value="${cat5e_props['wired-connection']['jitter']}"/>
    <xacro:property name="cat5e_packet_loss" value="${cat5e_props['wired-connection']['packet-loss']}"/>
    <xacro:property name="cat5e_reliability" value="${cat5e_props['wired-connection']['reliability']}"/>
    <xacro:property name="cat5e_availability" value="${cat5e_props['wired-connection']['availability']}"/>
    <xacro:property name="cat5e_throughput" value="${cat5e_props['wired-connection']['throughput']}"/>
    <xacro:property name="cat5e_qos_level" value="${cat5e_props['wired-connection']['qos-level']}"/>
    <xacro:property name="cat5e_energy_efficiency" value="${cat5e_props['wired-connection']['energy-efficiency']}"/>
    <xacro:property name="cat5e_compatibility" value="${cat5e_props['wired-connection']['compatibility']}"/>
    <xacro:property name="cat5e_cost" value="${cat5e_props['wired-connection']['cost']}"/>
    <xacro:property name="cat5e_scalability" value="${cat5e_props['wired-connection']['scalability']}"/>
    <xacro:property name="cat5e_security_level" value="${cat5e_props['wired-connection']['security-level']}"/>


    <xacro:macro name="cat5e_L2" params="id supporting_network supporting_node supporting_tp">
        <robot-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <supporting-termination-point>
                <network-ref>${supporting_network}</network-ref>
                <node-ref>${supporting_node}</node-ref>
                <tp-ref>${supporting_tp}</tp-ref>
            </supporting-termination-point>
            <layer2:l2-termination-point-attributes>
                <bandwidth>${cat5e_bandwidth}</bandwidth>
                <jitter>${cat5e_jitter}</jitter>
            </layer2:l2-termination-point-attributes>
        </robot-network-topology:termination-point>
    </xacro:macro>

    <xacro:macro name="cat5e_L1" params="id connector_type connector_format">
        <robot-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <layer1:l1-termination-point-attributes>
                <connector-type>${connector_type}</connector-type>
                <connector-format>${connector_format}</connector-format>
            </layer1:l1-termination-point-attributes>
        </robot-network-topology:termination-point>
    </xacro:macro>

</robot>