<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:nw="urn:network"
       xmlns:nt="urn:network-topology"
       xmlns:l1t="urn:layer1"
       xmlns:l2t="urn:layer2"
       name="nw_5g_rel15">

    <xacro:property name="nw_5g_rel15_yaml_file" value="$(find interface-description)/config/nw_5g_rel15.yaml" />
    <xacro:property name="nw_5g_rel15_props" value="${xacro.load_yaml(nw_5g_rel15_yaml_file)}"/>
    <xacro:property name="nw_5g_rel15_length" value="${nw_5g_rel15_props['wireless-connection']['length']}"/>
    <xacro:property name="nw_5g_rel15_bandwidth" value="${nw_5g_rel15_props['wireless-connection']['bandwidth']}"/>
    <xacro:property name="nw_5g_rel15_jitter" value="${nw_5g_rel15_props['wireless-connection']['jitter']}"/>
    <xacro:property name="nw_5g_rel15_packet_loss" value="${nw_5g_rel15_props['wireless-connection']['packet-loss']}"/>
    <xacro:property name="nw_5g_rel15_reliability" value="${nw_5g_rel15_props['wireless-connection']['reliability']}"/>
    <xacro:property name="nw_5g_rel15_availability" value="${nw_5g_rel15_props['wireless-connection']['availability']}"/>
    <xacro:property name="nw_5g_rel15_throughput" value="${nw_5g_rel15_props['wireless-connection']['throughput']}"/>
    <xacro:property name="nw_5g_rel15_qos_level" value="${nw_5g_rel15_props['wireless-connection']['qos-level']}"/>
    <xacro:property name="nw_5g_rel15_energy_efficiency" value="${nw_5g_rel15_props['wireless-connection']['energy-efficiency']}"/>
    <xacro:property name="nw_5g_rel15_compatibility" value="${nw_5g_rel15_props['wireless-connection']['compatibility']}"/>
    <xacro:property name="nw_5g_rel15_cost" value="${nw_5g_rel15_props['wireless-connection']['cost']}"/>
    <xacro:property name="nw_5g_rel15_scalability" value="${nw_5g_rel15_props['wireless-connection']['scalability']}"/>
    <xacro:property name="nw_5g_rel15_security_level" value="${nw_5g_rel15_props['wireless-connection']['security-level']}"/>


    <xacro:macro name="nw-5g-rel15_L1" params="id">
        <nt:termination-point>
            <nt:tp-id>${id}</nt:tp-id>
            <l1t:l1-termination-point-attributes>
                <l1t:intertface-type>nw_5g_rel15</l1t:intertface-type>
            </l1t:l1-termination-point-attributes>
        </nt:termination-point>
    </xacro:macro>

    <xacro:macro name="nw-5g-rel15_L2" params="id supporting_network supporting_node supporting_tp">
        <nt:termination-point>
            <nt:tp-id>${id}</nt:tp-id>
            <nt:supporting-termination-point>
                <nt:network-ref>${supporting_network}</nt:network-ref>
                <nt:node-ref>${supporting_node}</nt:node-ref>
                <nt:tp-ref>${supporting_tp}</nt:tp-ref>
            </nt:supporting-termination-point>
            <l2t:l2-termination-point-attributes>
                <l2t:bandwidth>${nw_5g_rel15_bandwidth}</l2t:bandwidth>
                <l2t:jitter>${nw_5g_rel15_jitter}</l2t:jitter>
            </l2t:l2-termination-point-attributes>
        </nt:termination-point>
    </xacro:macro>

</robot>