<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:robot-network-topology="urn:ietf:params:xml:ns:yang:robot-network-topology"
       xmlns:layer1="urn:ietf:params:xml:ns:yang:layer1"
       xmlns:layer2="urn:ietf:params:xml:ns:yang:layer2"
       name="nw_5g_rel15">

    <xacro:property name="nw_5g_rel15_yaml_file" value="$(find interface-description)/config/nw_5g_rel15.yaml" />
    <xacro:property name="nw_5g_rel15_props" value="${xacro.load_yaml(nw_5g_rel15_yaml_file)}"/>
    <xacro:property name="nw_5g_rel15_length" value="${nw_5g_rel15_props['wireless-connection']['length']}"/>
    <xacro:property name="nw_5g_rel15_bandwidth" value="${nw_5g_rel15_props['wireless-connection']['bandwidth']}"/>
    <xacro:property name="nw_5g_rel15_jitter" value="${nw_5g_rel15_props['wireless-connection']['jitter']}"/>
    <xacro:property name="nw_5g_rel15_packet_loss" value="${nw_5g_rel15_props['wireless-connection']['packet-loss']}"/>
    <xacro:property name="nw_5g_rel15_reliability" value="${nw_5g_rel15_props['wireless-connection']['reliability']}"/>
    <xacro:property name="nw_5g_rel15_availability" value="${nw_5g_rel15_props['wireless-connection']['availability']}"/>
    <xacro:property name="nw_5g_rel15_throughput" value="${nw_5g_rel15_props['wireless-connection']['throughput']}"/>
    <xacro:property name="nw_5g_rel15_qos_level" value="${nw_5g_rel15_props['wireless-connection']['qos-level']}"/>
    <xacro:property name="nw_5g_rel15_energy_efficiency" value="${nw_5g_rel15_props['wireless-connection']['energy-efficiency']}"/>
    <xacro:property name="nw_5g_rel15_compatibility" value="${nw_5g_rel15_props['wireless-connection']['compatibility']}"/>
    <xacro:property name="nw_5g_rel15_cost" value="${nw_5g_rel15_props['wireless-connection']['cost']}"/>
    <xacro:property name="nw_5g_rel15_scalability" value="${nw_5g_rel15_props['wireless-connection']['scalability']}"/>
    <xacro:property name="nw_5g_rel15_security_level" value="${nw_5g_rel15_props['wireless-connection']['security-level']}"/>

    <xacro:macro name="nw_5g_rel15_L2" params="id supporting_network supporting_node supporting_tp">
        <robot-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <supporting-termination-point>
                <network-ref>${supporting_network}</network-ref>
                <node-ref>${supporting_node}</node-ref>
                <tp-ref>${supporting_tp}</tp-ref>
            </supporting-termination-point>
            <layer2:l2-termination-point-attributes>
                <bandwidth>${nw_5g_rel15_bandwidth}</bandwidth>
                <jitter>${nw_5g_rel15_jitter}</jitter>
            </layer2:l2-termination-point-attributes>
        </robot-network-topology:termination-point>
    </xacro:macro>

    <xacro:macro name="nw_5g_rel15_L1" params="id connector_type connector_format">
        <robot-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <layer1:l1-termination-point-attributes>
                <connector-type>${connector_type}</connector-type>
                <connector-format>${connector_format}</connector-format>
            </layer1:l1-termination-point-attributes>
        </robot-network-topology:termination-point>
    </xacro:macro>

</robot>