<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:nw="urn:network"
       xmlns:nt="urn:network-topology"
       xmlns:l1t="urn:layer1"
       xmlns:l2t="urn:layer2"
       name="usb20">

    <xacro:property name="usb20_yaml_file" value="$(find interface-description)/config/usb20.yaml" />
    <xacro:property name="usb20_props" value="${xacro.load_yaml(usb20_yaml_file)}"/>
    <xacro:property name="usb20_length" value="${usb20_props['wired-connection']['length']}"/>
    <xacro:property name="usb20_bandwidth" value="${usb20_props['wired-connection']['bandwidth']}"/>
    <xacro:property name="usb20_jitter" value="${usb20_props['wired-connection']['jitter']}"/>
    <xacro:property name="usb20_packet_loss" value="${usb20_props['wired-connection']['packet-loss']}"/>
    <xacro:property name="usb20_reliability" value="${usb20_props['wired-connection']['reliability']}"/>
    <xacro:property name="usb20_availability" value="${usb20_props['wired-connection']['availability']}"/>
    <xacro:property name="usb20_throughput" value="${usb20_props['wired-connection']['throughput']}"/>
    <xacro:property name="usb20_qos_level" value="${usb20_props['wired-connection']['qos-level']}"/>
    <xacro:property name="usb20_energy_efficiency" value="${usb20_props['wired-connection']['energy-efficiency']}"/>
    <xacro:property name="usb20_compatibility" value="${usb20_props['wired-connection']['compatibility']}"/>
    <xacro:property name="usb20_cost" value="${usb20_props['wired-connection']['cost']}"/>
    <xacro:property name="usb20_scalability" value="${usb20_props['wired-connection']['scalability']}"/>
    <xacro:property name="usb20_security_level" value="${usb20_props['wired-connection']['security-level']}"/>


    <xacro:macro name="usb20_L1" params="id">

        <nt:termination-point>
            <nt:tp-id>${id}</nt:tp-id>
            <l1t:l1-termination-point-attributes>
                <l1t:interface-type>usb20</l1t:interface-type>
            </l1t:l1-termination-point-attributes>
        </nt:termination-point>
    </xacro:macro>

    <xacro:macro name="usb20_L2" params="id supporting_network supporting_node supporting_tp">

        <nt:termination-point>
            <nt:tp-id>${id}</nt:tp-id>
            <nt:supporting-termination-point>
                <nt:network-ref>${supporting_network}</nt:network-ref>
                <nt:node-ref>${supporting_node}</nt:node-ref>
                <nt:tp-ref>${supporting_tp}</nt:tp-ref>
            </nt:supporting-termination-point>
            <l2t:l2-termination-point-attributes>
                <l2t:bandwidth>${usb20_bandwidth}</l2t:bandwidth>
                <l2t:jitter>${usb20_jitter}</l2t:jitter>
            </l2t:l2-termination-point-attributes>
        </nt:termination-point>
    </xacro:macro>

</robot>