<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:robot-network-topology="urn:ietf:params:xml:ns:yang:robot-network-topology"
       xmlns:layer1="urn:ietf:params:xml:ns:yang:layer1"
       xmlns:layer2="urn:ietf:params:xml:ns:yang:layer2"
       name="wifi6">

    <xacro:property name="wifi6_yaml_file" value="$(find interface-description)/config/wifi6.yaml" />
    <xacro:property name="wifi6_props" value="${xacro.load_yaml(wifi6_yaml_file)}"/>
    <xacro:property name="wifi6_length" value="${wifi6_props['wireless-connection']['length']}"/>
    <xacro:property name="wifi6_bandwidth" value="${wifi6_props['wireless-connection']['bandwidth']}"/>
    <xacro:property name="wifi6_jitter" value="${wifi6_props['wireless-connection']['jitter']}"/>
    <xacro:property name="wifi6_packet_loss" value="${wifi6_props['wireless-connection']['packet-loss']}"/>
    <xacro:property name="wifi6_reliability" value="${wifi6_props['wireless-connection']['reliability']}"/>
    <xacro:property name="wifi6_availability" value="${wifi6_props['wireless-connection']['availability']}"/>
    <xacro:property name="wifi6_throughput" value="${wifi6_props['wireless-connection']['throughput']}"/>
    <xacro:property name="wifi6_qos_level" value="${wifi6_props['wireless-connection']['qos-level']}"/>
    <xacro:property name="wifi6_energy_efficiency" value="${wifi6_props['wireless-connection']['energy-efficiency']}"/>
    <xacro:property name="wifi6_compatibility" value="${wifi6_props['wireless-connection']['compatibility']}"/>
    <xacro:property name="wifi6_cost" value="${wifi6_props['wireless-connection']['cost']}"/>
    <xacro:property name="wifi6_scalability" value="${wifi6_props['wireless-connection']['scalability']}"/>
    <xacro:property name="wifi6_security_level" value="${wifi6_props['wireless-connection']['security-level']}"/>

    <xacro:macro name="wifi6" params="parent L2_network_id L1_network_id L2_id:=wifi6_L2 L1_id:=wifi6_L1"/>

    <xacro:macro name="wifi6_L2" params="id supporting_network supporting_node supporting_tp">
        <robot-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <supporting-termination-point>
                <network-ref>${supporting_network}</network-ref>
                <node-ref>${supporting_node}</node-ref>
                <tp-ref>${supporting_tp}</tp-ref>
            </supporting-termination-point>
            <layer2:l2-termination-point-attributes>
                <bandwidth>${wifi6_bandwidth}</bandwidth>
                <jitter>${wifi6_jitter}</jitter>
            </layer2:l2-termination-point-attributes>
        </robot-network-topology:termination-point>
    </xacro:macro>

    <xacro:macro name="wifi6_L1" params="id connector_type connector_format">
        <robot-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <layer1:l1-termination-point-attributes>
                <connector-type>${connector_type}</connector-type>
                <connector-format>${connector_format}</connector-format>
            </layer1:l1-termination-point-attributes>
        </robot-network-topology:termination-point>
    </xacro:macro>

</robot>