<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:nw="urn:robot-network"
       xmlns:nt="urn:robot-network-topology"
       xmlns:l1t="urn:layer1"
       xmlns:l2t="urn:layer2"
       name="wifi6">

    <xacro:property name="wifi6_yaml_file" value="$(find interface-description)/config/wifi6.yaml" />
    <xacro:property name="wifi6_props" value="${xacro.load_yaml(wifi6_yaml_file)}"/>
    <xacro:property name="wifi6_length" value="${wifi6_props['wireless-connection']['length']}"/>
    <xacro:property name="wifi6_bandwidth" value="${wifi6_props['wireless-connection']['bandwidth']}"/>
    <xacro:property name="wifi6_jitter" value="${wifi6_props['wireless-connection']['jitter']}"/>
    <xacro:property name="wifi6_packet_loss" value="${wifi6_props['wireless-connection']['packet-loss']}"/>
    <xacro:property name="wifi6_reliability" value="${wifi6_props['wireless-connection']['reliability']}"/>
    <xacro:property name="wifi6_availability" value="${wifi6_props['wireless-connection']['availability']}"/>
    <xacro:property name="wifi6_throughput" value="${wifi6_props['wireless-connection']['throughput']}"/>
    <xacro:property name="wifi6_qos_level" value="${wifi6_props['wireless-connection']['qos-level']}"/>
    <xacro:property name="wifi6_energy_efficiency" value="${wifi6_props['wireless-connection']['energy-efficiency']}"/>
    <xacro:property name="wifi6_compatibility" value="${wifi6_props['wireless-connection']['compatibility']}"/>
    <xacro:property name="wifi6_cost" value="${wifi6_props['wireless-connection']['cost']}"/>
    <xacro:property name="wifi6_scalability" value="${wifi6_props['wireless-connection']['scalability']}"/>
    <xacro:property name="wifi6_security_level" value="${wifi6_props['wireless-connection']['security-level']}"/>

    <xacro:macro name="wifi6" params="parent L2_network_id L1_network_id L2_id:=wifi6_L2 L1_id:=wifi6_L1"/>

    <xacro:macro name="wifi6_L2" params="id supporting_network supporting_node supporting_tp">
        <nt:termination-point>
            <nt:tp-id>${id}</nt:tp-id>
            <nt:supporting-termination-point>
                <nt:network-ref>${supporting_network}</nt:network-ref>
                <nt:node-ref>${supporting_node}</nt:node-ref>
                <nt:tp-ref>${supporting_tp}</nt:tp-ref>
            </nt:supporting-termination-point>
            <l2t:l2-termination-point-attributes>
                <l2t:bandwidth>${wifi6_bandwidth}</l2t:bandwidth>
                <l2t:jitter>${wifi6_jitter}</l2t:jitter>
            </l2t:l2-termination-point-attributes>
        </nt:termination-point>
    </xacro:macro>

    <xacro:macro name="wifi6_L1" params="id connector_type connector_format">
        <nt:termination-point>
            <nt:tp-id>${id}</nt:tp-id>
            <l1t:l1-termination-point-attributes>
                <l1t:connector-type>${connector_type}</l1t:connector-type>
                <l1t:connector-format>${connector_format}</l1t:connector-format>
            </l1t:l1-termination-point-attributes>
        </nt:termination-point>
    </xacro:macro>

</robot>