<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:nw="urn:network"
       xmlns:nt="urn:network-topology"
       xmlns:l1t="urn:layer1"
       xmlns:l2t="urn:layer2"
       name="wifi4">

    <xacro:property name="wifi4_yaml_file" value="$(find interface-description)/config/wifi4.yaml" />
    <xacro:property name="wifi4_props" value="${xacro.load_yaml(wifi4_yaml_file)}"/>
    <xacro:property name="wifi4_length" value="${wifi4_props['wireless-connection']['length']}"/>
    <xacro:property name="wifi4_bandwidth" value="${wifi4_props['wireless-connection']['bandwidth']}"/>
    <xacro:property name="wifi4_jitter" value="${wifi4_props['wireless-connection']['jitter']}"/>
    <xacro:property name="wifi4_packet_loss" value="${wifi4_props['wireless-connection']['packet-loss']}"/>
    <xacro:property name="wifi4_reliability" value="${wifi4_props['wireless-connection']['reliability']}"/>
    <xacro:property name="wifi4_availability" value="${wifi4_props['wireless-connection']['availability']}"/>
    <xacro:property name="wifi4_throughput" value="${wifi4_props['wireless-connection']['throughput']}"/>
    <xacro:property name="wifi4_qos_level" value="${wifi4_props['wireless-connection']['qos-level']}"/>
    <xacro:property name="wifi4_energy_efficiency" value="${wifi4_props['wireless-connection']['energy-efficiency']}"/>
    <xacro:property name="wifi4_compatibility" value="${wifi4_props['wireless-connection']['compatibility']}"/>
    <xacro:property name="wifi4_cost" value="${wifi4_props['wireless-connection']['cost']}"/>
    <xacro:property name="wifi4_scalability" value="${wifi4_props['wireless-connection']['scalability']}"/>
    <xacro:property name="wifi4_security_level" value="${wifi4_props['wireless-connection']['security-level']}"/>


    <xacro:macro name="wifi4_L1" params="id">
        <nt:termination-point>
            <nt:tp-id>${id}</nt:tp-id>
            <l1t:l1-termination-point-attributes>
                <l1t:intertface-type>wifi4</l1t:intertface-type>
            </l1t:l1-termination-point-attributes>
        </nt:termination-point>
    </xacro:macro>

    <xacro:macro name="wifi4_L2" params="id supporting_network supporting_node supporting_tp">
        <nt:termination-point>
            <nt:tp-id>${id}</nt:tp-id>
            <nt:supporting-termination-point>
                <nt:network-ref>${supporting_network}</nt:network-ref>
                <nt:node-ref>${supporting_node}</nt:node-ref>
                <nt:tp-ref>${supporting_tp}</nt:tp-ref>
            </nt:supporting-termination-point>
            <l2t:l2-termination-point-attributes>
                <l2t:bandwidth>${wifi4_bandwidth}</l2t:bandwidth>
                <l2t:jitter>${wifi4_jitter}</l2t:jitter>
            </l2t:l2-termination-point-attributes>
        </nt:termination-point>
    </xacro:macro>

</robot>