<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:ietf-network-topology="urn:ietf:params:xml:ns:yang:ietf-network-topology"
       xmlns:device-layer="urn:ietf:params:xml:ns:yang:device-layer"
       xmlns:network-layer="urn:ietf:params:xml:ns:yang:network-layer"
       name="wifi4">

    <xacro:property name="wifi4_yaml_file" value="$(find interface_description)/config/wifi4.yaml" />
    <xacro:property name="wifi4_props" value="${xacro.load_yaml(wifi4_yaml_file)}"/>
    <xacro:property name="wifi4_type" value="${wifi4_props['wireless-connection']['type']}"/>
    <xacro:property name="wifi4_length" value="${wifi4_props['wireless-connection']['length']}"/>
    <xacro:property name="wifi4_bandwidth" value="${wifi4_props['wireless-connection']['bandwidth']}"/>
    <xacro:property name="wifi4_jitter" value="${wifi4_props['wireless-connection']['jitter']}"/>
    <xacro:property name="wifi4_packet_loss" value="${wifi4_props['wireless-connection']['packet-loss']}"/>
    <xacro:property name="wifi4_reliability" value="${wifi4_props['wireless-connection']['reliability']}"/>
    <xacro:property name="wifi4_availability" value="${wifi4_props['wireless-connection']['availability']}"/>
    <xacro:property name="wifi4_throughput" value="${wifi4_props['wireless-connection']['throughput']}"/>
    <xacro:property name="wifi4_qos_level" value="${wifi4_props['wireless-connection']['qos-level']}"/>
    <xacro:property name="wifi4_energy_efficiency" value="${wifi4_props['wireless-connection']['energy-efficiency']}"/>
    <xacro:property name="wifi4_compatibility" value="${wifi4_props['wireless-connection']['compatibility']}"/>
    <xacro:property name="wifi4_cost" value="${wifi4_props['wireless-connection']['cost']}"/>
    <xacro:property name="wifi4_scalability" value="${wifi4_props['wireless-connection']['scalability']}"/>
    <xacro:property name="wifi4_security_level" value="${wifi4_props['wireless-connection']['security-level']}"/>

    <xacro:macro name="wifi4" params="parent L2_network_id L1_network_id L2_id:=wifi4_L2 L1_id:=wifi4_L1"/>

    <xacro:macro name="wifi4_L2" params="id supporting_network supporting_node supporting_tp">
        <ietf-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <supporting-termination-point>
                <network-ref>${supporting_network}</network-ref>
                <node-ref>${supporting_node}</node-ref>
                <tp-ref>${supporting_tp}</tp-ref>
            </supporting-termination-point>
            <network-layer:network-layer-termination-point-attributes>
                <tp-type>${wifi4_type}</tp-type>
                <bandwidth>${wifi4_bandwidth}</bandwidth>
                <jitter>${wifi4_jitter}</jitter>
                <packet_loss>${wifi4_packet_loss}</packet_loss>
                <reliability>${wifi4_reliability}</reliability>
                <cost>${wifi4_cost}</cost>
            </network-layer:network-layer-termination-point-attributes>
        </ietf-network-topology:termination-point>
    </xacro:macro>

    <xacro:macro name="wifi4_L1" params="id connector_type connector_format">
        <ietf-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <device-layer:device-layer-termination-point-attributes>
                <connector-type>${connector_type}</connector-type>
                <connector-format>${connector_format}</connector-format>
            </device-layer:device-layer-termination-point-attributes>
        </ietf-network-topology:termination-point>
    </xacro:macro>

</robot>