<?xml version="1.0" encoding="UTF-8" ?>
<robot xmlns:xacro="http://ros.org/wiki/xacro"
       xmlns:ietf-network-topology="urn:ietf:params:xml:ns:yang:ietf-network-topology"
       xmlns:device-layer="urn:ietf:params:xml:ns:yang:device-layer"
       xmlns:network-layer="urn:ietf:params:xml:ns:yang:network-layer"
       name="wifi5">

    <xacro:property name="wifi5_yaml_file" value="$(find interface_description)/config/wifi5.yaml" />
    <xacro:property name="wifi5_props" value="${xacro.load_yaml(wifi5_yaml_file)}"/>
    <xacro:property name="wifi5_type" value="${wifi5_props['wireless-connection']['type']}"/>
    <xacro:property name="wifi5_length" value="${wifi5_props['wireless-connection']['length']}"/>
    <xacro:property name="wifi5_bandwidth" value="${wifi5_props['wireless-connection']['bandwidth']}"/>
    <xacro:property name="wifi5_jitter" value="${wifi5_props['wireless-connection']['jitter']}"/>
    <xacro:property name="wifi5_packet_loss" value="${wifi5_props['wireless-connection']['packet-loss']}"/>
    <xacro:property name="wifi5_reliability" value="${wifi5_props['wireless-connection']['reliability']}"/>
    <xacro:property name="wifi5_availability" value="${wifi5_props['wireless-connection']['availability']}"/>
    <xacro:property name="wifi5_throughput" value="${wifi5_props['wireless-connection']['throughput']}"/>
    <xacro:property name="wifi5_qos_level" value="${wifi5_props['wireless-connection']['qos-level']}"/>
    <xacro:property name="wifi5_energy_efficiency" value="${wifi5_props['wireless-connection']['energy-efficiency']}"/>
    <xacro:property name="wifi5_compatibility" value="${wifi5_props['wireless-connection']['compatibility']}"/>
    <xacro:property name="wifi5_cost" value="${wifi5_props['wireless-connection']['cost']}"/>
    <xacro:property name="wifi5_scalability" value="${wifi5_props['wireless-connection']['scalability']}"/>
    <xacro:property name="wifi5_security_level" value="${wifi5_props['wireless-connection']['security-level']}"/>

    <xacro:macro name="wifi5" params="parent L2_network_id L1_network_id L2_id:=wifi5_L2 L1_id:=wifi5_L1"/>

    <xacro:macro name="wifi5_L2" params="id supporting_network supporting_node supporting_tp">
        <ietf-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <supporting-termination-point>
                <network-ref>${supporting_network}</network-ref>
                <node-ref>${supporting_node}</node-ref>
                <tp-ref>${supporting_tp}</tp-ref>
            </supporting-termination-point>
            <network-layer:network-layer-termination-point-attributes>
                <tp-type>${wifi5_type}</tp-type>
                <bandwidth>${wifi5_bandwidth}</bandwidth>
                <jitter>${wifi5_jitter}</jitter>
                <packet_loss>${wifi5_packet_loss}</packet_loss>
                <reliability>${wifi5_reliability}</reliability>
                <cost>${wifi5_cost}</cost>
            </network-layer:network-layer-termination-point-attributes>
        </ietf-network-topology:termination-point>
    </xacro:macro>

    <xacro:macro name="wifi5_L1" params="id connector_type connector_format">
        <ietf-network-topology:termination-point>
            <tp-id>${id}</tp-id>
            <device-layer:device-layer-termination-point-attributes>
                <connector-type>${connector_type}</connector-type>
                <connector-format>${connector_format}</connector-format>
            </device-layer:device-layer-termination-point-attributes>
        </ietf-network-topology:termination-point>
    </xacro:macro>
    
</robot>